version: '3'

services:
  refchef:
    image: brownccv/sh-refchef
    volumes:
      - ./:/root/scratch/new/
    working_dir: /root/scratch/
    command:
      - /bin/bash
      - -c
      - refchef-cook --git_local git/ -o data/ --new new/refchef_* --execute &&
        refchef-menu -m git/master.yaml
