# This is a basic workflow to help you get started with Actions

name: yaml_form

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    inputs:
      response:
        description: form_response
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          python-version: 3.9      
      # Runs a single command using the runners shell
      - name: MakeYaml
        run: "echo '${{ github.event.client_payload.response}}' > new_ref.yaml"
      - name: checkMD5
        run: (md5sum new_ref.yaml | (awk '{print $1}'))       
      - name: NewBranch
        run: |
          git config --global user.email 'joselynn_wallace@brown.edu'
          git config --global user.name 'joselynn wallace'
          git checkout -B `(md5sum new_ref.yaml | (awk '{print $1}'))`
          python parser.py 
          git add new_parsed.yaml
          git commit -m 'adding new_parsed.yaml'
          git push --set-upstream origin `(md5sum new_parsed.yaml | (awk '{print $1}'))`
