name: yaml_form
on:
  repository_dispatch:
    inputs:
      response:
        description: form_response
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  
      - run: pip install -r requirements.txt
      - name: MakeYaml
        run: "echo '${{ github.event.client_payload.response}}' > new_ref.yaml"
      - name: CheckMD5
        run: (md5sum new_ref.yaml | (awk '{print $1}'))       
      - name: NewBranch
        run: |
          git config --global user.email 'joselynn_wallace@brown.edu'
          git config --global user.name 'joselynn wallace'
          git checkout -B `(md5sum new_ref.yaml | (awk '{print $1}'))`
          python parser.py 
          git add .
          git commit -m 'adding new_parsed.yaml'
          git push --set-upstream origin `(md5sum new_ref.yaml | (awk '{print $1}'))`
